"""update table audio_file

Revision ID: 7037cd2ade7b
Revises: 7f170713b917
Create Date: 2023-07-20 13:53:50.017385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7037cd2ade7b'
down_revision = '7f170713b917'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'audio_file', ['name_file'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audio_file', type_='unique')
    # ### end Alembic commands ###
