"""update table audio_file

Revision ID: 7f170713b917
Revises: cd72d79cab10
Create Date: 2023-07-20 13:48:02.950827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f170713b917'
down_revision = 'cd72d79cab10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_file', sa.Column('name_file', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_file', 'name_file')
    # ### end Alembic commands ###
