"""update table audio_file

Revision ID: cd72d79cab10
Revises: 55a7f5462204
Create Date: 2023-07-19 23:55:01.756658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd72d79cab10'
down_revision = '55a7f5462204'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
